export const orETHStake = [
  {
    type: "constructor",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "gasManager", type: "address", internalType: "address" },
      { name: "orETH", type: "address", internalType: "address" },
      { name: "osETH", type: "address", internalType: "address" },
      { name: "rey", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "BLAST",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IBlast" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DAY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MINSTAKE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ORETH",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "OSETH",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RATIO",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "REY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumYieldPool",
    inputs: [{ name: "nativeYield", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "avgStakeDays",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calcOSETHAmount",
    inputs: [
      {
        name: "amountInORETH",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimMaxGas",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
    outputs: [{ name: "gasAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "extendLockTime",
    inputs: [
      { name: "positionId", type: "uint256", internalType: "uint256" },
      { name: "extendDays", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "amountInREY", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forceUnstakeFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gasManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "idCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "outETHVault_",
        type: "address",
        internalType: "address",
      },
      {
        name: "forceUnstakeFee_",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minLockupDays_",
        type: "uint16",
        internalType: "uint16",
      },
      { name: "maxLockupDays_", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialized",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxLockupDays",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minLockupDays",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "outETHVault",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionsOf",
    inputs: [{ name: "positionId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IORETHStakeManager.Position",
        components: [
          {
            name: "orETHAmount",
            type: "uint104",
            internalType: "uint104",
          },
          {
            name: "osETHAmount",
            type: "uint104",
            internalType: "uint104",
          },
          { name: "deadline", type: "uint40", internalType: "uint40" },
          { name: "closed", type: "bool", internalType: "bool" },
          { name: "owner", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "readGasBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setForceUnstakeFee",
    inputs: [
      {
        name: "forceUnstakeFee_",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxLockupDays",
    inputs: [{ name: "maxLockupDays_", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinLockupDays",
    inputs: [{ name: "minLockupDays_", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOutETHVault",
    inputs: [{ name: "outETHVault_", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stake",
    inputs: [
      {
        name: "amountInORETH",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "lockupDays", type: "uint16", internalType: "uint16" },
      {
        name: "positionOwner",
        type: "address",
        internalType: "address",
      },
      { name: "osETHTo", type: "address", internalType: "address" },
      { name: "reyTo", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "amountInOSETH",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "amountInREY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalStaked",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalYieldPool",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferGasManager",
    inputs: [
      {
        name: "newGasManager",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unstake",
    inputs: [{ name: "positionId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "amountInORETH",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawYield",
    inputs: [{ name: "burnedREY", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "yieldAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ClaimMaxGas",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "gasAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExtendLockTime",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "extendDays",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newDeadLine",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "mintedREY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GasManagerTransferred",
    inputs: [
      {
        name: "previousGasManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newGasManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetForceUnstakeFee",
    inputs: [
      {
        name: "forceUnstakeFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMaxLockupDays",
    inputs: [
      {
        name: "maxLockupDays",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMinLockupDays",
    inputs: [
      {
        name: "minLockupDays",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetOutETHVault",
    inputs: [
      {
        name: "outETHVault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StakeORETH",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amountInORETH",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountInOSETH",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountInREY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unstake",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amountInORETH",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "burnedOSETH",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "burnedREY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawYield",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "burnedREY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "yieldAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AddressEmptyCode",
    inputs: [{ name: "target", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AddressInsufficientBalance",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "FailedInnerCall", inputs: [] },
  { type: "error", name: "ForceUnstakeFeeOverflow", inputs: [] },
  { type: "error", name: "InvalidExtendDays", inputs: [] },
  {
    type: "error",
    name: "InvalidGasManager",
    inputs: [{ name: "gasManager", type: "address", internalType: "address" }],
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  {
    type: "error",
    name: "InvalidLockupDays",
    inputs: [
      {
        name: "minLockupDays",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxLockupDays",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  { type: "error", name: "InvalidReduceDays", inputs: [] },
  {
    type: "error",
    name: "MinStakeInsufficient",
    inputs: [{ name: "minStake", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "PermissionDenied", inputs: [] },
  { type: "error", name: "PositionClosed", inputs: [] },
  {
    type: "error",
    name: "ReachedDeadline",
    inputs: [{ name: "deadline", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "UnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ZeroInput", inputs: [] },
] as const;
