export const orUSDStake = [
  {
    type: "constructor",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "gasManager", type: "address", internalType: "address" },
      { name: "orUSD", type: "address", internalType: "address" },
      { name: "osUSD", type: "address", internalType: "address" },
      { name: "ruy", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BLAST",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IBlast" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DAY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MINSTAKE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ORUSD",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "OSUSD",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RATIO",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RUY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "USDB",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumYieldPool",
    inputs: [{ name: "nativeYield", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "avgStakeDays",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calcOSUSDAmount",
    inputs: [
      {
        name: "amountInORUSD",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimMaxGas",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
    outputs: [{ name: "gasAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "extendLockTime",
    inputs: [
      { name: "positionId", type: "uint256", internalType: "uint256" },
      { name: "extendDays", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "amountInRUY", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forceUnstakeFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gasManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "idCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "outUSDBVault_",
        type: "address",
        internalType: "address",
      },
      {
        name: "forceUnstakeFee_",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minLockupDays_",
        type: "uint16",
        internalType: "uint16",
      },
      { name: "maxLockupDays_", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialized",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxLockupDays",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minLockupDays",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "outUSDBVault",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionsOf",
    inputs: [{ name: "positionId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IORUSDStakeManager.Position",
        components: [
          {
            name: "orUSDAmount",
            type: "uint104",
            internalType: "uint104",
          },
          {
            name: "osUSDAmount",
            type: "uint104",
            internalType: "uint104",
          },
          { name: "deadline", type: "uint40", internalType: "uint40" },
          { name: "closed", type: "bool", internalType: "bool" },
          { name: "owner", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "readGasBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setForceUnstakeFee",
    inputs: [
      {
        name: "forceUnstakeFee_",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxLockupDays",
    inputs: [{ name: "maxLockupDays_", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinLockupDays",
    inputs: [{ name: "minLockupDays_", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOutUSDBVault",
    inputs: [
      {
        name: "outUSDBVault_",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stake",
    inputs: [
      {
        name: "amountInORUSD",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "lockupDays", type: "uint16", internalType: "uint16" },
      {
        name: "positionOwner",
        type: "address",
        internalType: "address",
      },
      { name: "osUSDTo", type: "address", internalType: "address" },
      { name: "ruyTo", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "amountInOSUSD",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "amountInRUY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalStaked",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalYieldPool",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferGasManager",
    inputs: [
      {
        name: "newGasManager",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unstake",
    inputs: [{ name: "positionId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "amountInORUSD",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawYield",
    inputs: [{ name: "amountInRUY", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "yieldAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ClaimMaxGas",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "gasAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExtendLockTime",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "extendDays",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newDeadLine",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "mintedRUY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GasManagerTransferred",
    inputs: [
      {
        name: "previousGasManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newGasManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetForceUnstakeFee",
    inputs: [
      {
        name: "forceUnstakeFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMaxLockupDays",
    inputs: [
      {
        name: "maxLockupDays",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMinLockupDays",
    inputs: [
      {
        name: "minLockupDays",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetOutUSDBVault",
    inputs: [
      {
        name: "outUSDBVault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StakeORUSD",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amountInORUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountInOSUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountInRUY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unstake",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amountInORUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "burnedOSUSD",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "burnedRUY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawYield",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "burnedRUY",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "yieldAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AddressEmptyCode",
    inputs: [{ name: "target", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AddressInsufficientBalance",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "FailedInnerCall", inputs: [] },
  { type: "error", name: "ForceUnstakeFeeOverflow", inputs: [] },
  { type: "error", name: "InvalidExtendDays", inputs: [] },
  {
    type: "error",
    name: "InvalidGasManager",
    inputs: [{ name: "gasManager", type: "address", internalType: "address" }],
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  {
    type: "error",
    name: "InvalidLockupDays",
    inputs: [
      {
        name: "minLockupDays",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxLockupDays",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  { type: "error", name: "InvalidReduceDays", inputs: [] },
  {
    type: "error",
    name: "MinStakeInsufficient",
    inputs: [{ name: "minStake", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "PermissionDenied", inputs: [] },
  { type: "error", name: "PositionClosed", inputs: [] },
  {
    type: "error",
    name: "ReachedDeadline",
    inputs: [{ name: "deadline", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "UnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ZeroInput", inputs: [] },
] as const;
